### ISSUE TITLE
OmniTool change with custom-model

### ISSUE THREAD

**Issue by HiddenSeaMC** [BG-Software-LLC/WildTools#115]
### Minecraft's Version

1.18.2 Spigot

### Plugin's Version

2.13.0

### Describe the bug

When i use the 

"omni_tool", my custom model switch.

Like, i have the pickaxe with the custom model, when i break grass the custom_model switch to a diamond shovel
when i break again stone it come back to custom_model

### To Reproduce

setup a custom model data

use the omni tool

break dirt see that the custom model data disappears

break again stone and see it's coming back

**Comment by OmerBenGera** [comment]
I tested it and the custom model data persists when the tool types changes.

**Comment by HiddenSeaMC** [comment]
Hey,

I will send you the video of showing i have an issue and my config.
Maybe it can help you

Issue: https://youtu.be/S6fVqtvqjso
Config: 

```
  MultiTool:
    tool-mode: SORT
    auto-collect: true
    spigot-unbreakable: true
    omni-tool: true
    type: DIAMOND_PICKAXE
    custom-model: 10001
    name: '&7• &fMultiTool'
    lore:
    - '&f'
    enchants:
    - 'DIG_SPEED:5'
```
