### ISSUE TITLE
WildTools working on WorldGuard protected area

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildTools#128]
### Minecraft's Version

[17:35:53 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version

### Plugin's Version

[17:36:08 INFO]: WildTools version 2.13.1.80

### Describe the bug

Players can sell and harvest crops on protected area via WorldGuard.
They don't have permissions to break, place or anything in the region.

I tested with SuperiorSkyblock2 and the bug is not working inside the island region, only in the WorldGuard region.

### To Reproduce

I use these flags:
![image](https://user-images.githubusercontent.com/41546701/185181999-fe9168a7-d3f9-4595-b7a3-12ae16d0bb49.png)

HARVESTER tool

```
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
  - WorldGuard
  - SuperiorSkyblock2
  # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins: []
```

[17:40:54 INFO]: WorldGuard version 7.0.7+216b061
