### ISSUE TITLE
5x5 pickaxe with mending breaking randomly

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildTools#136]
### Minecraft's Version

1.12 paper

### Plugin's Version

2022.7-b87

### Describe the bug

A lot of my players are reporting that pickaxes that are 5x5 with mending are breaking even with 150 durability
https://imgur.com/a/LtANq89

### To Reproduce

```
  cluster_pickaxe:
    tool-mode: CUBOID
    break-level: 5
    only-same-type: false
    unbreakable: false
    type: DIAMOND_PICKAXE
    name: '&4&l*&c&l*&f&l* &c&lCLUSTER &f&l*&c&l*&4&l*'
    lore:
    - '&8Ritka Tárgy'
    - ''
    - '&7Ez a csákány képes 5x5'
    - '&7területen bányászni!'
    enchants:
    - DIG_SPEED:5
    - LOOT_BONUS_BLOCKS:4
    - DURABILITY:7
    blacklisted-blocks:
    - MOB_SPAWNER
    - STATIONARY_LAVA
    - LAVA
    - STATIONARY_WATER
    - WATER
    - CHEST
    - DIAMOND_BLOCK
    - EMERALD_BLOCK
    - LAPIS_BLOCK
    - REDSTONE_BLOCK
    - HAY_BLOCK
    - SPONGE
    - ENDER_PORTAL_FRAME
    - COAL_BLOCK
    - BEACON
    - IRON_BLOCK
    - HOPPER
    blacklisted-drops:
    - STONE
    - COBBLESTONE
    - DIRT
    - GRAVEL
    - DIAMOND
    - EMERALD
    - REDSTONE
    - INK_SACK:4
    - COAL
    - GOLD_ORE
    - IRON_ORE
```
