### ISSUE TITLE
WildTools 2024.4: Pickaxe Trenching Not Breaking Andesite, Granite, Diorite in 1.20.4

### ISSUE THREAD

**Issue by DimaSergeew** [BG-Software-LLC/WildTools#215]
### Minecraft's Version

1.20.4

### Plugin's Version

2024.4

### Describe the bug

The pickaxe trenching feature in WildTools 2024.4 is not breaking blocks such as Andesite, Granite, and Diorite in Minecraft version 1.20.4. Adjusting the plugin's configuration settings does not resolve the issue. The trenching function simply does not work on these block types.

### To Reproduce

- Install WildTools 2024.4 in Minecraft version 1.20.4.
- Configure the plugin for trenching with a pickaxe.
- Attempt to use the pickaxe trenching function on Andesite, Granite, or Diorite blocks.
- Notice that the blocks remain unbroken.

### Additional Information

- Plugin version: WildTools 2024.4
- Minecraft version: 1.20.4
- Configuration changes have been tested but do not solve the issue.

**Comment by OmerBenGera** [comment]
Upload your config file to pastebin and send a link to it here. Also, let me know which tool you talk about in your config file

**Comment by DimaSergeew** [comment]
```yml
####################################################
##                                                ##
##            WildTools Configuration             ##
##               Developed by Ome_R               ##
##                                                ##
####################################################

# Choose which prices plugin to check for prices:
# Auto, CMI, EconomyShopGUI, Essentials, ExcellentShop, GUIShop, newtShop, NextGens, QuantumShop, ShopGUIPlus, zShop
prices-plugin: 'ShopGUIPlus'

# Path to the logs file.
# You may disable it by setting the path to be empty.
logs-file: ''

# A list of prices. Use "TYPE" and "TYPE:DATA" formats.
prices-list:
- 'STONE:5' #Each stone will cost $5
- 'LOG:0:5' #Only oak logs will cost $5

# Here you can configure which plugins will be called, etc.
# Optimizing the lists will result better performance!
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
    - EXAMPLE_PLUGIN
  # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins: []

# The plugin brings a lot of options and features for making tools easily with rich-configuration options.
# The default config has basic trench-pickaxe, tray-pickaxe, sand-wand, sell-wand, lightning-wand, harvester-hoe
# and cannon-wand examples. Each tool-mode has it's own configuration options, make sure you don't mix them.
#
# *** Builder Tool-Mode ***
# Tools in this mode will create a pillar of the same block as the clicked one.
# Required sections:
# length: The length of the pillar (INTEGER)
#
# *** Cannon Tool-Mode ***
# Tools in this mode will fill all dispensers in a selected area with tnt. This mode is used for cannon-wands.
# Right-click and left-click to select an area.
# Required sections:
# tnt-amount: How many tnt will be filled in each dispenser? (INTEGER)
#
# *** Crafting Tool-Mode ***
# Tools in this mode will auto-craft items in a container.
# Required sections:
# craftings: All the crafting *results* for the tool (LIST)
#      Please follow the "TYPE" or "TYPE:DATA" format for results.
#
# *** Crowbar Tool-Mode ***
# Tools in this mode will break spawners and drop them.
# Optional sections:
# commands-on-use: A command that will be ran when using the crowbar on a spawner.
#                 Use %player% for player's name and %entity% for entity's type.
#
# *** Cuboid Tool-Mode ***
# Tools in this mode will dig a cuboid-area (for example, 3x3x3). This mode is used for trench and tray pickaxes.
# Required sections:
# break-level: How big the cuboid-area gonna be (3 will be 3x3x3 area) [INTEGER]
#
# *** Drain Tool-Mode ***
# Tools in this mode will remove all ice blocks in the checking area.
# Required sections:
# radius: What is the radius of the checking area? (3 will check a 7x7x7 area) (INTEGER)
#
# *** Harvester Tool-Mode ***
# Tools in this mode will harvest seeds and replant them automatically. This mode is used for harvester-hoes.
# Drops support silk-touch and fortune.
# Required sections:
# radius: What is the radius of the checking area? (3 will check a 7x7x7 area) (INTEGER)
# Optional sections:
# farmland-radius: What is the radius of the checking for dirt area? (Same as radius)
# active-action: Which action should activate the harvester? (RIGHT_CLICK or LEFT_CLICK)
# multiplier: Multiply the earnings from the sell mode.
# one-layer-only: Make the radius only affect the x and z axis, without the y axis.
#
# *** Ice Tool-Mode ***
# Tools in this mode will smelt all ice blocks in the checking area.
# Required sections:
# radius: What is the radius of the checking area? (3 will check a 7x7x7 area) (INTEGER)
#
# *** Lightning Tool-Mode ***
# Tools in this mode will strike a lightning to charge creepers. This mode is used for lightning-wands.
#
# *** Magnet Tool-Mode ***
# Tools in this mode will suction items into the player's inventory.
# Required sections:
# radius: What is the radius of the checking area? (INTEGER)
#
# *** Pillar Tool-Mode ***
# Tools in this mode will dig a pillar of blocks with the same type. This mode is used for sand-wands.
#
# *** Sell Tool-Mode ***
# Tools in this mode will sell all the container's contents. This mode is used for sell-wands.
# Optional sections:
# multiplier: Multiply the earnings from a chest.
#
# *** Sort Tool-Mode ***
# Tools in this mode will sort all the clicked chest's contents.
#
# There are sections that can be applied for all the tools:
# cooldown: Cool-down between uses in milliseconds (INTEGER) (Default 0)
# auto-collect: Drops will go straight into the inventory (BOOLEAN) (Default false)
# instant-break: Blocks will be broken instantly (BOOLEAN) (Default false)
# silk-touch: Tool will have a hidden silk-touch enchantment (BOOLEAN) (Default false)
# only-same-type: Only blocks with the same type will be dug. (BOOLEAN) (Default false)
# only-inside-claim: Will only work on blocks inside claim land.
# unbreakable: Tool will never be broken (BOOLEAN) (Default false)
# vanilla-damage: Tool will be damaged by vanilla actions (BOOLEAN) (Default false)
# spigot-unbreakable: Set spigot's unbreakable flag (BOOLEAN) (Default false)
# custom-model: Set a custom model for the tool. (INTEGER) (Default null)
# omni-tool: Tool will change it's type depends on broken block (BOOLEAN) (Default false)
#      Tool's default type must be a tool, such as pickaxe, shovel or axe.
# uses: Custom durability for the tool (INTEGER)
#      If both unbreakable and uses are not set, tool will use the vanilla durability (supports unbreaking enchantment)
# uses-progress: Whether or not the durability of the tool should be decreased in relation to the uses.
#      This is only a cosmetic feature, and will not affect the amount of uses of the tools.
# keep-inventory: Tool won't get dropped from players inventory (BOOLEAN) (Default false)
# private: Should tool be assigned to only one player? (BOOLEAN) (Default false)
# anvil-combine-exp: Amount of exp required to combine tool with another (INTEGER) (Default -1)
# anvil-combine-limit: Maximum uses for the combined tool (INTEGER) (Default -1)
# type: Material type (Check https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
# name: Custom name for the tool (STRING)
# lore: Custom lore for the tool (LIST)
# glow: Glow effect for the tool (BOOLEAN)
# enchants: Enchantments for the tool (LIST)
#      Please follow the "ENCHANTMENT:LEVEL" format for enchantments.
#      (Check https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html)
# whitelisted-blocks: Which blocks will be dug by the tool? [LIST]
# blacklisted-blocks: Which blocks won't be dug by the tool? [LIST]
# whitelisted-drops: Which items will be dropped by the tool? [LIST]
# blacklisted-drops: Which items won't be dropped by the tool? [LIST]
#      Please follow the "TYPE" or "TYPE:DATA" format for drops and blocks.
# blacklisted-worlds: A list of worlds that the tool will not work inside. [LIST]
# whitelisted-worlds: A list of worlds that the tool will only work inside. [LIST]
# notified-plugins: A list of plugins that should be notified when blocks are broken. [LIST]
# statistics: Should broken blocks be counted towards the statistics of the player? (BOOLEAN) (Default true)

tools:
  trench_pickaxe4x4:
    tool-mode: CUBOID
    break-level: 4
    only-same-type: true
    unbreakable: true
    type: DIAMOND_PICKAXE
    name: '&f --{ &a&lТраншейная кирка &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Эта кирка пробивает туннель размером 4x4'
    - '&f'
    - '&a&l Блоки из черного списка:'
    - '&f - &7Mob Spawner'
    - '&f'
    - '&7 Будут выпадать только рудные капли'
    - '&8&m---------------------------------------'
    enchants:
    - 'DIG_SPEED:5'
    blacklisted-blocks:
    - 'MOB_SPAWNER'
    - 'CRYING_OBSIDIAN'
    - 'OBSIDIAN'
    - 'CHEST'
    - 'ENDER_CHEST'
    - 'SHULKER_BOX'
    - 'BARREL'
    - 'lodestone'
    - 'gold_block'
    - 'diamond_block'
    - 'red_mushroom_block'
    whitelisted-drops:
    - 'COAL'
    - 'IRON_ORE'
    - 'GOLD_ORE'
    - 'REDSTONE'
    - 'INK_SACK:4'
    - 'DIAMOND'
    - 'EMERALD'
    - 'QUARTZ'
  trench_pickaxe3x3:
    tool-mode: CUBOID
    break-level: 3
    only-same-type: true
    unbreakable: true
    type: DIAMOND_PICKAXE
    name: '&f --{ &a&lТраншейная кирка &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Эта кирка пробивает туннель размером 3x3'
    - '&f'
    - '&a&l Блоки из черного списка:'
    - '&f - &7Mob Spawner'
    - '&f'
    - '&7 Будут выпадать только рудные капли'
    - '&8&m---------------------------------------'
    enchants:
    - 'DIG_SPEED:5'
    blacklisted-blocks:
    - 'MOB_SPAWNER'
    - 'CRYING_OBSIDIAN'
    - 'OBSIDIAN'
    - 'CHEST'
    - 'ENDER_CHEST'
    - 'SHULKER_BOX'
    - 'BARREL'
    - 'lodestone'
    - 'gold_block'
    - 'diamond_block'
    - 'red_mushroom_block'
    whitelisted-drops:
    - 'COAL'
    - 'IRON_ORE'
    - 'GOLD_ORE'
    - 'REDSTONE'
    - 'INK_SACK:4'
    - 'DIAMOND'
    - 'EMERALD'
    - 'QUARTZ'
    ```
