### ISSUE TITLE
Harvester Hoe Statistics

### ISSUE THREAD

**Issue by JessyDrew** [BG-Software-LLC/WildTools#225]
### Minecraft's Version

[17:05:11 INFO]: This server is running Paper version 1.21.1-127-master@14a48cd (2024-10-20T23:19:03Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

WildTools-2024.4

### Describe the bug

I have enabled Statistics: true in my harvester hoe config, but when I harvest my carrots, it doesn't count.

### To Reproduce

 ```
 harvester_hoe:
    tool-mode: HARVESTER
    radius: 0
    auto-collect: true
    statistics: true
    type: DIAMOND_HOE
    uses: 500
    name: '&f --{ &d&lHarvester Hoe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Click on a block to harvest, replant'
    - '&7 seeds and turn dirt into farmlands.'
    - '&7'
    - '&d&l Uses:'
    - '&f   {}'
    - '&f'
    - '&8&m---------------------------------------'
    whitelisted-blocks:
    - CARROTS
```
And:
`/papi parse me %statistic_mine_block:carrots%`
