### ISSUE TITLE
The tool is not consumed

### ISSUE THREAD

**Issue by CraftedLore** [BG-Software-LLC/WildTools#229]
### Minecraft's Version

1.21.0
Paper

### Plugin's Version

Latest

### Describe the bug

Hi, I noticed a small inconsistency.

An example with the trench_pickaxe, in case you wanted this tool to be consumed when used, it does.

It happens that at the end of the uses, (that is, when it should break/disappear), the tool is still usable, but when it is in use it eliminates the blocks in a strange way without being consumed anyway.
The same happens when I decide to use the maximum uses of the tool, that is, with 1 uses remaining the tool is perfectly usable without ever reaching 0

Furthermore, when the tool uses the maximum uses, it does not receive damage from being consumed

I would really like to collaborate to be able to resolve this incongruence. I will start by saying that it could also be my lack of attention to not having configured something well, but in case I wanted to let you know about the problem I am encountering. Thanks.

### To Reproduce

EXAMPLE n.1

```

tools:
  trench_pickaxe:
    tool-mode: CUBOID
    break-level: 3
    only-same-type: false
    unbreakable: false
    type: STONE_PICKAXE
    name: '&f --{ &a&lTrench Pickaxe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 This pickaxe breaks a tunnel of 3x3.'
    - '&f'
    - '&a&l Blacklisted Blocks:'
    - '&f - &7Mob Spawner'
    - '&f'
    - '&7 Only ore-drops will be dropped.'
    - '&8&m---------------------------------------'
    enchants:
    - 'DIG_SPEED:5'
    blacklisted-blocks:
    - 'MOB_SPAWNER'
    whitelisted-drops:
    - 'COAL'
    - 'IRON_ORE'
    - 'GOLD_ORE'
    - 'REDSTONE'
    - 'INK_SACK:4'
    - 'DIAMOND'
    - 'EMERALD'
    - 'QUARTZ'

```

EXAMPLE n.2

```
  trench_pickaxe:
    tool-mode: CUBOID
    break-level: 3
    only-same-type: false
    unbreakable: false
    uses: 10
    type: STONE_PICKAXE
    name: '&f --{ &a&lTrench Pickaxe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 This pickaxe breaks a tunnel of 3x3.'
    - '&f'
    - '&a&l Blacklisted Blocks:'
    - '&f - &7Mob Spawner'
    - '&f'
    - '&7 Only ore-drops will be dropped.'
    - '&c&l USES LEFT'
    - '&7{}'
    - '&8&m---------------------------------------'
    enchants:
    - 'DIG_SPEED:5'
    blacklisted-blocks:
    - 'MOB_SPAWNER'
    whitelisted-drops:
    - 'COAL'
    - 'IRON_ORE'
    - 'GOLD_ORE'
    - 'REDSTONE'
    - 'INK_SACK:4'
    - 'DIAMOND'
    - 'EMERALD'
    - 'QUARTZ'
```

![Image](https://github.com/user-attachments/assets/c0950ae8-d740-47f9-bd97-56411b7a9913)

![Image](https://github.com/user-attachments/assets/bc0011a9-4b49-4c39-8cec-b97e7e71b32a)

![Image](https://github.com/user-attachments/assets/4fd2703c-cbf4-48de-98e0-68acb3583e2a)

### Additional Information

![Image](https://github.com/user-attachments/assets/c0950ae8-d740-47f9-bd97-56411b7a9913)

![Image](https://github.com/user-attachments/assets/bc0011a9-4b49-4c39-8cec-b97e7e71b32a)

![Image](https://github.com/user-attachments/assets/4fd2703c-cbf4-48de-98e0-68acb3583e2a)
